/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary-fixed": "#dce1ff",
        "on-surface-variant": "#444651",
        "secondary-fixed": "#e1e0ff",
        "surface-container-low": "#f2f4f6",
        "tertiary": "#4b1c00",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#341100",
        "surface-container-high": "#e6e8ea",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-error": "#ffffff",
        "surface-dim": "#d8dadc",
        "primary": "#00236f",
        "outline-variant": "#c5c5d3",
        "tertiary-container": "#6e2c00",
        "inverse-surface": "#2d3133",
        "success-green": "#10B981",
        "on-secondary-fixed": "#07006c",
        "on-surface": "#191c1e",
        "on-primary-container": "#90a8ff",
        "primary-fixed-dim": "#b6c4ff",
        "on-secondary": "#ffffff",
        "text-primary": "#0F172A",
        "surface-white": "#FFFFFF",
        "primary-container": "#1e3a8a",
        "inverse-primary": "#b6c4ff",
        "surface-container": "#eceef0",
        "on-primary-fixed": "#00164e",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb691",
        "surface-tint": "#4059aa",
        "outline": "#757682",
        "background": "#f7f9fb",
        "on-primary-fixed-variant": "#264191",
        "text-secondary": "#64748B",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-container": "#fffbff",
        "surface": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "security-blue": "#1E293B",
        "secondary-fixed-dim": "#c0c1ff",
        "on-background": "#191c1e",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed": "#ffdbcb",
        "on-tertiary-container": "#f39461",
        "on-tertiary-fixed-variant": "#773205",
        "secondary-container": "#6063ee",
        "border-subtle": "#E2E8F0",
        "secondary": "#4648d4"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "max-width": "1280px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "unit": "4px",
        "margin-desktop": "32px"
      },
      "fontFamily": {
        "body-md": ["Inter"],
        "label-md": ["Geist"],
        "label-sm": ["Geist"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Geist"],
        "display-lg": ["Geist"],
        "headline-lg": ["Geist"],
        "title-md": ["Geist"]
      },
      "fontSize": {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.03em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
